### ISSUE TITLE
Feature Request: Add a Landing Page for the Uber-like Application

### ISSUE THREAD

**Issue by sezallagwal** [visheshrwl/Uber-like#69]
## Description
To enhance the user experience and give a professional first impression, we need to add a dedicated landing page to the application. This page will serve as the entry point for new and returning users, showcasing the core features and value of the application.

### Expected Sections on the Landing Page
1. **Hero Section**
   - Display a welcome message or tagline, such as "Seamless Rides, Simplified Experience."
   - Include a call-to-action button (e.g., "Get Started" or "Book a Ride Now").

2. **FAQs**
   - Add a list of frequently asked questions to address common user concerns.

3. **Footer**
   - Include links to other pages such as Terms & Conditions, Privacy Policy, Contact Us, and social media links.

### Design Considerations
- Ensure a responsive and modern design that works seamlessly on both desktop and mobile devices.
- Use high-quality visuals and a layout consistent with the rest of the application.

---

Please assign this issue under the `gssoc-ext` and `hacktoberfest` labels.

<!-- 2. **Features Overview**
   - Highlight the primary features, such as:
     - Easy ride booking and management
     - Real-time tracking
     - Transparent fare breakdown
     - Reliable driver network

3. **Testimonials**
   - Showcase feedback from existing users to build credibility.

4. **How It Works**
   - Provide a step-by-step guide on how to book a ride, view ride history, and access receipts.

5. **Pricing Information**
   - Brief overview of fare structure and any available discounts or offers. --!>

**Comment by visheshrwl** [comment]
Hey @sezallagwal , I’ve added the level 3 tag to this PR since you've addressed such a high-priority aspect of the application. Your understanding of this issue as a core component for improving the user experience shows exactly the insight we’re looking for.

Focus on metrics like First Contentful Paint (FCP), Response Time (RTI), Largest Contentful Paint (LCP), First Input Delay (FID), Page Load Time, Rendering Speed, Network Latency, Time to First Byte (TTFB), Cumulative Layout Shift (CLS), and Total Blocking Time (TBT). Excited to see your final implementation!

All the best as you finalize this—looking forward to seeing your excellent implementation!!! 👍✨

**Comment by sezallagwal** [comment]
okay i will look into that

**Comment by visheshrwl** [comment]
Hey @sezallagwal ! 👋

First off, I want to extend a huge thank you to all of you for your amazing contributions to this project! Your support and hard work mean a lot, and I truly appreciate everything you do. 🙏

I have a small favor to ask: if you think I’ve been helpful and supportive throughout your contributions, I would be honored if you could nominate me by filling out this form: [Nominate me](https://docs.google.com/forms/d/e/1FAIpQLSdnqJ5crpQFQEQXGTzekfKUxOJCXkSx8AykqvvHzlqBcNGMAQ/viewform).

Your nomination would mean the world to me, and it’s a great way to help me continue supporting our awesome community. Thanks again for all the amazing work, and let's keep making great things happen! 🚀

Best,
Vishesh
