### ISSUE TITLE
Implement Issue Reminder Workflow🚀

### ISSUE THREAD

**Issue by amiya-cyber** [visheshrwl/Uber-like#84]
Description: Create a GitHub Actions workflow that sends reminders on open issues without updates. The workflow should post a comment prompting assignees to take action.

Expected Benefits:

Improved responsiveness and prioritization of tasks.
Increased overall productivity.

please assign me with level3 label @visheshrwl

**Comment by visheshrwl** [comment]
Hey @amiya-cyber , thanks for your enthusiasm! I’m assigning this to you with a level 2 label because, while valuable, it focuses on workflow automation and notification setup, which are relatively straightforward in scope. For level 3, we typically look for tasks involving more complex designs, multi-system integrations, or significant architectural changes.

Looking forward to seeing your improvements in action—thanks again for the initiative!
